- src/request.js
adds getters to req for httpVersion, httpVersionMajor, and httpVersionMinor
uws.js has no method to get http version but it only handles 1.1 anyways
> add req.httpVersion, req.httpVersionMajor, and req.httpVersionMinor

- tests/index.js
now uses promisified `childProcess.exec`, with a timeout of 60 secs
also, for some reason, making it async made it log differently so i removed the `testDescription` and OK/FAIL logging since it does it by itself now (it arguably looks better, i have no idea why it did that though)
> add timeout to tests (async)

- src/application.js
In vanilla Express the `listen()` method return HTTP server
> Listen must return HTTP server

- src/router.js
- src/utils.js
[cache compilation of regex](https://github.com/dimdenGD/ultimate-express/pull/31/commits/910cc9fb6784ecc81db1238e9f6e447368589d7e) 
Store the compilation of regex into a variable
[better performance with replaceAll](https://github.com/dimdenGD/ultimate-express/pull/31/commits/3e6afe4ff20e3f12892f04f6bb8a8e3e146ae2c1) 
String.prototype.replaceAll has better performance instead of regex
> perf: Cache of compiled regex

- src/utils.js
No need to parse query if the query is empty
> perf: don't parse query if query is empty

- .github/workflows/test.yml
- .gitignore
- package-lock.json
- package.json
- tests/tests/middlewares/express-fileupload-temp.js
- tests/tests/middlewares/express-fileupload.js
- tests/tests/middlewares/multer.js
- tests/tests/middlewares/multiple-middlewares.js
Matrix testing for backward compatibility is essential to ensure the stability and reliability of the product across different Node.js versions. I have also bumped the node engine dependency to 18, since the uws version used, doesn't support 16
> feat: matrix testing

- src/router.js
- src/utils.js
Regex are slower and `(?:)` is always true! no need to test it!
> perf: avoid useless regex into route resolution

- src/utils.js
from https://github.com/expressjs/express/pull/6066
> Use loop for acceptParams

- src/request.js
- No need to declare a new variable `const accept = accepts({ headers: this.headers });` https://github.com/dimdenGD/ultimate-express/pull/56/commits/e8bb956a85535c2580a19acdcb0b9697c071909e
- No need to create a `object accepts({ headers: this.headers })` https://github.com/dimdenGD/ultimate-express/pull/56/commits/6ff51e6b4d54f685845317873b9f30b3396e80c6
**Bonus Improvements**:
- Maybe we can also cache `accepts(this)` initialization, see https://github.com/dimdenGD/ultimate-express/pull/56#issuecomment-2480818321
> perf: simplify req.accepts*

- src/router.js
- src/utils.js
fix: EMPTY_REGEX control. fullMountpath is a RegEx not a string, the replace is always executed.
perf: fast check for empty RegEx. No need to check for source, just check if EMPTY_REGEX object
perf: fast getFullMountpath on empty middleware
> fix/perf: EMPTY_REGEX control

- README.md
> docs: add info to prevent 431 Request Header Fields Too Large

- src/response.js
fix https://github.com/dimdenGD/ultimate-express/issues/106
from https://www.rfc-editor.org/rfc/rfc2109
> the Set-Cookie response header comprises the token Set-Cookie:, followed by a comma-separated list of one or more cookies.
> fix: use "," instead of ";" as separator of multiple cookie

- .gitignore
- .nycrc.json
- package.json
This PR introduce the test coverage.
With
```
npm run test:coverage
```
after the test, will generate the coverage in the console output:
```
----------------|---------|----------|---------|---------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
File            | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------------|---------|----------|---------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
> feat: test coverage

- package-lock.json
- package.json
The coverage isn't accurate because `nyc` write the report when `process.exit` is called and each test call `process.exit`
This PR collect the coverage on each test and write the report on the end (if all test success)
```
npm run cover
```
If the report doesn't write, manually run:
```
npm run cover:report
```
Current coverage
After this PR
All the command introduced
1.  `cover`: `cover:unit` + `cover:report`
2.  `cover:unit`: run the test with `nyc` (collect coverage info)
3.  `cover:report`: generate the html report base on the collected info
> fix: coverage

- tests/index.js
- before
```
✔ must support urlencoded body parser (158.008503ms)
✔ middlewares (2177.171754ms)
ℹ tests 13
ℹ suites 0
ℹ pass 13
ℹ fail 0
ℹ cancelled 0
ℹ skipped 0
ℹ todo 0
ℹ duration_ms 2179.437333
```
- after
```
...
✔ must support urlencoded body parser (194.166462ms)
﹣ must support compression middleware with big file OFF (0.374146ms) # SKIP
✔ must support compression middleware (268.503454ms)
...
✔ middlewares (12990.847715ms)
ℹ tests 46
ℹ suites 0
ℹ pass 45
ℹ fail 0
ℹ cancelled 0
ℹ skipped 1
ℹ todo 0
ℹ duration_ms 12993.111067
```
> fixup skipping test

- package-lock.json
- package.json
update `@types/express` to 4.17.21 (latest for version 4)
maybe also fix https://github.com/dimdenGD/ultimate-express/issues/72 but need feedback from user
> chore(typescript): update express type

- tests/tests/res/res-socket.js
Original test is
```js
app.get('/test', (req, res) => {
console.log(res.socket.writable); // expected true
res.end();
console.log(res.socket.writable); // expected false
});
```
it works on ultimate-express (`true` `false`), on express is: `true` `true`
this test just check socket property is defined.
I don't know if the correct behaviour is `true` `true` (express)
> chore: add test res.socket

- tests/tests/res/errors.js
close https://github.com/dimdenGD/ultimate-express/issues/166
Side notes:
1) with declarative response the behaviour is 
```
Server is running on port 13333
Hello WorldHello World
```
2) I don't check the error string because isn't the same equal message
> chore(test): error response was already sent

- src/response.js
- src/router.js
https://nodejs.org/api/timers.html#timeoutunref
> When called, the active Timeout object will not require the Node.js event loop to remain active. If there is no other activity keeping the event loop running, the process may exit before the Timeout object's callback is invoked. 
It's just a best practice. No need to wait the timer completition if user need to kill the process (eg. restart)
> chore: unref timers

- src/response.js
https://developer.mozilla.org/en-US/docs/Web/API/Performance/now
> Date.now() may have been impacted by system and user clock adjustments
This fixes a small chance that a system clock change will occur while writing to the stream.
fix https://github.com/dimdenGD/ultimate-express/issues/215
> fix(timestamp): use performance.now()

- src/request.js
The problem in issue #86 was solved by the same person, but was not applied. At the moment the problem is actual and prevents work when using the `moleculer-web` package.
> fix: add setter for baseUrl (#86)

- package-lock.json
- src/index.js
some named exports are missing, which breaks [compatibility with express](https://github.com/expressjs/express/blob/master/lib/express.js#L58-L81) when using named imports in ESM eg:
```js
import { Router } from 'ultimate-express';
```
which currently will throw:
```
SyntaxError: Named export 'Router' not found. The requested module 'ultimate-express' is a CommonJS module, which may not support all module.exports as named exports.
```
> re-export some named exports for compatibility
