src/response.js

just res.json()s objects instead

fix res.send() with objects not setting content-type to application/json

---

package.json
src/router.js

just adds resolve(true) like it was before

fix preprocessRequest

---

package-lock.json
package.json

install bytes module

---

README.md

Good work on drop-in replacement of Express ;)

docs(readme): module name fix

---

package-lock.json
package.json
src/types.d.ts

This adds the types for the settings arguments for `express()`

Add types for the settings

---

.vscode/launch.json
demo/index.js
package-lock.json
package.json

Add new developing command for run a demo server with debugger enabled
```
npm run dev
```
Also add vscode setting for attach to process for debug and launch demo

chore: add demo and vscode setting for debug help

---

src/middlewares.js

fix: shared references for large bodies.

---

tests/tests/res/res-write-head.js

avoid https://github.com/dimdenGD/ultimate-express/pull/89

feat: add test to res.writeHead()

---

src/response.js

old is true at line https://github.com/dimdenGD/ultimate-express/edit/main/src/response.js#L567 no need to check at line https://github.com/dimdenGD/ultimate-express/edit/main/src/response.js#L571

chore: removed alway true if

---

README.md

Just add link to other online benchmark 
Fourth in https://www.techempower.com/benchmarks/ only javascript framework
First in https://web-frameworks-benchmark.netlify.app/result only javascript framework
Congratulations @dimdenGD !!

docs: add other benchmark

---

src/request.js

feat: add setter for query and headers

---

tests/tests/res/res-format.js

Add test for missing cases in format method
+1% coverage
Master
PR

chore: add missing test on res.format

---

tests/tests/res/res-send-file.js

Add missing case to test sendFile (see https://github.com/dimdenGD/ultimate-express/issues/122)

chore: test e-tag and dotfile

---

tests/tests/res/res-jsonp-array.js

chore: add test for jsonp array

---

.nycrc.json

chore: remove worker from coverage

---

README.md
package-lock.json
package.json
tests/tests/middlewares/morgan.js

close https://github.com/dimdenGD/ultimate-express/issues/127

chore: test morgan

---

tests/tests/routers/operator.js

test some routing operator from https://expressjs.com/en/guide/routing.html

chore: test some routing operator

---

tests/tests/res/res-custom-etag.js

chore(test): add case for custom etag fn

---

tests/tests/res/res-send-file.js

complete https://github.com/dimdenGD/ultimate-express/pull/124

fix(test): etag case not coverd if "etag fn" is truthy

---

tests/tests/res/res-jsonp-array.js

fix https://github.com/dimdenGD/ultimate-express/pull/125
I have misunderstanding how array of callback in jsonp works

fix(test): fixed misunderstanding of array of callback case

---

tests/tests/req/req-param.js

chore(test): add missing case of read param into json body

---

src/utils.js
tests/tests/routers/multi-params.js

fix https://github.com/dimdenGD/ultimate-express/issues/158

fix(routing): multi param route

---

src/router.js
tests/tests/routers/operator.js

fix https://github.com/dimdenGD/ultimate-express/issues/161

chore: test routing (very hard)

---

tests/tests/routers/operator.js

now coverage is **88.97%** (before this PR is 87.05%) +2%

chore: improve test by check all request property

---

src/response.js
tests/tests/res/res-write-head.js

fix https://github.com/dimdenGD/ultimate-express/issues/170

fix(chaining): writeHead return this

---

package-lock.json
package.json
tests/tests/middlewares/graphql-http.js

see https://github.com/dimdenGD/ultimate-express/issues/170

chore(test): graphql-http middleware

---

tests/tests/res/res-connection.js

cover response.js (cover close to 90%):

chore(test): must support res.connection

---

src/view.js
tests/parts/sub-template/index.pug
tests/tests/engines/pug.js

chore(test): view method

---

src/response.js
tests/tests/req/req-fresh.js

fix https://github.com/dimdenGD/ultimate-express/issues/197

fix: emit if fresh

---

src/router.js
tests/tests/req/req-url-nested.js

fix https://github.com/dimdenGD/ultimate-express/issues/194

fix: unnamed param

---

src/response.js
tests/tests/middlewares/body-json.js
tests/tests/middlewares/body-raw-deflate.js
tests/tests/middlewares/body-raw-gzip.js
tests/tests/middlewares/body-raw.js
tests/tests/middlewares/body-sizes.js
tests/tests/middlewares/body-text-utf16.js
tests/tests/middlewares/body-text.js
tests/tests/middlewares/body-type.js
tests/tests/res/declarative-content-type.js
tests/tests/res/piping.js
tests/tests/res/res-download.js
tests/tests/res/res-end.js
tests/tests/res/res-format.js
tests/tests/res/res-json.js
tests/tests/res/res-send-file.js
tests/tests/res/res-write.js
tests/tests/send-file/large-file.js
tests/tests/send-file/simple.js

fix https://github.com/dimdenGD/ultimate-express/issues/193 
fix https://github.com/dimdenGD/ultimate-express/issues/195
this is the important changes (In the others I have added into 15 tests the check of content-type)

fix: default content type

---

src/response.js
tests/tests/middlewares/passport.js
tests/tests/res/res-redirect.js

fix https://github.com/dimdenGD/ultimate-express/issues/196

fix: redirect

---

src/response.js
tests/tests/res/res-end-declarative.js
tests/tests/res/res-send-declarative.js

fix https://github.com/dimdenGD/ultimate-express/pull/207

fix: content type

---

src/types.d.ts

related to https://github.com/dimdenGD/ultimate-ws/pull/8

extend app.uwsApp type
